// [snowpack] add styles to the page (skip if no document exists)
if (typeof document !== 'undefined') {
  const code = "@import url(\"https://fonts.googleapis.com/css2?family=Hind:wght@300;700&display=swap\");\nbody {\n  background-color: #444444;\n  font-family: \"Hind\", sans-serif;\n}\n\nbutton {\n  z-index: 9999;\n}\n\n#overlay {\n  display: none;\n}\n\n#tutorial,\n#overlay {\n  width: calc(100% - 20px);\n  background: #f1f1f1;\n  border-radius: 10px;\n  margin: 10px;\n  position: absolute;\n}\n#tutorial .interface__header,\n#overlay .interface__header {\n  display: flex;\n  justify-content: flex-start;\n  align-items: center;\n  background: burlywood;\n  padding: 0px 10px;\n  border-radius: 10px;\n}\n#tutorial .interface__box,\n#overlay .interface__box {\n  padding: 10px;\n  margin: 10px;\n  background: #ccc;\n  border-radius: 10px;\n}\n#tutorial .interface__box.iphone,\n#overlay .interface__box.iphone {\n  padding: 5px 10px;\n  background-color: brown;\n  color: white;\n}\n#tutorial .iphone-disclamer,\n#overlay .iphone-disclamer {\n  font-size: 12px;\n  text-align: center;\n}\n#tutorial .logo,\n#overlay .logo {\n  width: auto;\n  height: 70px;\n  margin-right: 40px;\n}\n#tutorial h1,\n#overlay h1 {\n  text-align: center;\n}\n\n/* Show the DOM Overlay element while active (:xr-overlay pseudoclass) */\nbody:xr-overlay #overlay {\n  display: initial;\n  padding: 0;\n  margin: 0;\n}\nbody:xr-overlay #overlay h1 {\n  margin: 0;\n  padding: 0;\n}\nbody:xr-overlay #overlay .interface__buttons {\n  display: none;\n  padding: 10px;\n  margin: 10px;\n  background: #ccc;\n  border-radius: 10px;\n}\nbody:xr-overlay #overlay .interface__buttons.active {\n  display: block;\n}\nbody:xr-overlay #overlay .interface__buttons.active .grid-buttons {\n  display: flex;\n  justify-content: space-between;\n}\nbody:xr-overlay #overlay .interface__search {\n  display: none;\n  padding: 10px;\n  margin: 10px;\n  background: #ccc;\n  border-radius: 10px;\n}\nbody:xr-overlay #overlay .interface__search.active {\n  display: block;\n}\nbody:xr-overlay #overlay .interface__ar-btn.active {\n  background: red;\n}\nbody:xr-overlay #overlay .interface__preset {\n  margin: 10px 0 0;\n}\nbody:xr-overlay #tutorial {\n  display: none;\n}";

  const styleEl = document.createElement("style");
  const codeEl = document.createTextNode(code);
  styleEl.type = 'text/css';
  styleEl.appendChild(codeEl);
  document.head.appendChild(styleEl);
}